#!/usr/bin/env python3
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent


def get_all_py_files():
    py_files = []
    for root, dirs, files in os.walk(PROJECT_ROOT):
        for file in files:
            if file.endswith(".py"):
                full_path = Path(root) / file
                py_files.append(full_path)
    return sorted(py_files)


def get_all_json_files():
    json_files = []
    for root, dirs, files in os.walk(PROJECT_ROOT):
        for file in files:
            if file.endswith(".json"):
                full_path = Path(root) / file
                json_files.append(full_path)
    return sorted(json_files)


def main():
    # Merge all Python files
    py_files = get_all_py_files()
    print(f"Found {len(py_files)} .py files to merge (ALL files).")

    output_path = PROJECT_ROOT / "all_python_merged.py"
    with open(output_path, "w", encoding="utf-8") as outfile:
        outfile.write("# ALL Bolt Python files merged\\n")
        outfile.write(
            "# This file contains the concatenation of EVERY .py file in the project\\n"
        )
        outfile.write("# Generated by Hermes Agent\\n\\n")

        for py_file in py_files:
            rel_path = py_file.relative_to(PROJECT_ROOT)
            outfile.write(
                f"# =============================================================================\\n"
            )
            outfile.write(f"# File: {rel_path}\\n")
            outfile.write(
                f"# =============================================================================\\n"
            )
            try:
                with open(py_file, "r", encoding="utf-8") as infile:
                    content = infile.read()
                outfile.write(content)
                if not content.endswith("\\n"):
                    outfile.write("\\n")
                outfile.write("\\n\\n")
            except Exception as e:
                outfile.write(f"# ERROR reading {py_file}: {e}\\n\\n")

    print(f"Written all Python files to {output_path}")

    # Merge all JSON files
    json_files = get_all_json_files()
    print(f"Found {len(json_files)} .json files to merge (ALL files).")

    json_output_path = PROJECT_ROOT / "all_json_merged.txt"
    with open(json_output_path, "w", encoding="utf-8") as outfile:
        outfile.write("# ALL Bolt JSON files merged\\n")
        outfile.write(
            "# This file contains the concatenation of EVERY .json file in the project\\n"
        )
        outfile.write("# Generated by Hermes Agent\\n\\n")

        for json_file in json_files:
            rel_path = json_file.relative_to(PROJECT_ROOT)
            outfile.write(
                f"# =============================================================================\\n"
            )
            outfile.write(f"# File: {rel_path}\\n")
            outfile.write(
                f"# =============================================================================\\n"
            )
            try:
                with open(json_file, "r", encoding="utf-8") as infile:
                    content = infile.read()
                outfile.write(content)
                if not content.endswith("\\n"):
                    outfile.write("\\n")
                outfile.write("\\n\\n")
            except Exception as e:
                outfile.write(f"# ERROR reading {json_file}: {e}\\n\\n")

    print(f"Written all JSON files to {json_output_path}")


if __name__ == "__main__":
    main()
