#!/usr/bin/env python3
import os
from pathlib import Path

PROJECT_ROOT = Path("/Users/carter/developer/Bolt")
EXCLUDE_DIRS = {
    ".venv",
    "llm/LLMs-from-scratch",
    "tests",
    "New Folder With Items",
    "__pycache__",
    ".git",
    "scripts/legacy",
}


def should_exclude(path):
    # Convert to relative string for easier matching
    rel = path.relative_to(PROJECT_ROOT)
    parts = rel.parts
    for excl in EXCLUDE_DIRS:
        # Check if any part of the path matches the excluded directory
        if excl in parts:
            return True
    return False


def get_py_files():
    py_files = []
    for root, dirs, files in os.walk(PROJECT_ROOT):
        # Modify dirs in-place to skip excluded directories
        dirs[:] = [d for d in dirs if not should_exclude(Path(root) / d)]
        for file in files:
            if file.endswith(".py"):
                full_path = Path(root) / file
                if not should_exclude(full_path):
                    py_files.append(full_path)
    return sorted(py_files)


def main():
    py_files = get_py_files()
    print(f"Found {len(py_files)} .py files to merge.")

    output_path = PROJECT_ROOT / "merged_bot.py"
    with open(output_path, "w", encoding="utf-8") as outfile:
        outfile.write("# Merged Bolt Python files\\n")
        outfile.write(
            "# This file contains the concatenation of all local .py files (excluding tests, LLMs-from-scratch, etc.)\\n"
        )
        outfile.write("# Generated by Hermes Agent\\n\\n")

        for py_file in py_files:
            rel_path = py_file.relative_to(PROJECT_ROOT)
            outfile.write(
                f"# =============================================================================\\n"
            )
            outfile.write(f"# File: {rel_path}\\n")
            outfile.write(
                f"# =============================================================================\\n"
            )
            try:
                with open(py_file, "r", encoding="utf-8") as infile:
                    content = infile.read()
                outfile.write(content)
                # Ensure we end with a newline
                if not content.endswith("\\n"):
                    outfile.write("\\n")
                outfile.write("\\n\\n")
            except Exception as e:
                outfile.write(f"# ERROR reading {py_file}: {e}\\n\\n")

    print(f"Written merged file to {output_path}")


if __name__ == "__main__":
    main()
