#!/usr/bin/env python3
"""
Daily Briefing with Nexus + Vector DB
"""

import os
import sys
from pathlib import Path
from datetime import datetime

# Ensure paths
REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "Core"))

def main(print_only=False):
    OUTPUT_DIR = Path("Docs/briefings/daily")
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    
    briefing_text = f"# Bolt Daily Briefing\n\n**{datetime.now().strftime('%A, %B %d, %Y')}**\n\n"
    
    # Queue, storage, recent clips, etc. (your existing code)
    briefing_text += "## Queue Status\n\n**Clips ready to post:** 0\n\n*No clips currently in queue.*\n\n---\n\n"
    briefing_text += "## Storage Status\n\n| Directory | Size |\n|-----------|------|\n| Recordings | 114GB |\n\n---\n\n"
    
    # NEW: Nexus + Vector DB enrichment
    try:
        from modules.Nexus_Creator import NexusCreator
        nexus = NexusCreator()
        nexus_result = nexus.consult(
            "Morning priorities, content plan, and action items",
            context="Current queue, recent performance, M-tier progress",
            task_type="strategy",
            complexity="high"
        )
        strategy_insight = nexus_result["advice"]
        briefing_text += f"🎯 NEXUS STRATEGY INSIGHT:\n{strategy_insight}\n\n---\n\n"
    except Exception as e:
        print(f"Nexus enrichment skipped: {e}")
    
    # Rest of your briefing (action items, quick commands, etc.)
    briefing_text += "## Action Items For Today\n\n1. Review recent clips\n2. Process new recordings\n\n"
    briefing_text += f"*Generated by Bolt at {datetime.now().strftime('%I:%M %p')}*"
    
    # Save and print
    output_file = OUTPUT_DIR / "latest_morning.md"
    output_file.write_text(briefing_text, encoding="utf-8")
    
    if print_only:
        print(briefing_text)
    else:
        print("Briefing saved to", output_file)

if __name__ == "__main__":
    print_only = "--print" in sys.argv
    main(print_only=print_only)