#!/usr/bin/env python3
"""
Weekly Analysis with Nexus + Vector DB
"""

import os
import sys
from pathlib import Path
from datetime import datetime

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "Core"))

def main(print_only=False):
    report = f"# Bolt Weekly Analysis\n\n**Week ending {datetime.now().strftime('%B %d, %Y')}**\n\n"
    
    # Your existing performance summary code...
    report += "## Performance Summary\n\n(Your existing content here)\n\n"
    
    # NEW: Nexus enrichment
    try:
        from modules.Nexus_Creator import NexusCreator
        nexus = NexusCreator()
        nexus_result = nexus.consult(
            "Weekly insights and next week recommendations",
            context="Recent performance data",
            task_type="strategy",
            complexity="high"
        )
        weekly_insight = nexus_result["advice"]
        report += f"📈 NEXUS WEEKLY RECOMMENDATIONS:\n{weekly_insight}\n\n"
    except Exception as e:
        print(f"Nexus enrichment skipped: {e}")
    
    # Rest of report...
    report += "*Generated by Bolt*"
    
    if print_only:
        print(report)
    else:
        print("Weekly report generated.")

if __name__ == "__main__":
    print_only = "--print" in sys.argv
    main(print_only=print_only)